"""
Schemas Module

This module defines Pydantic models for request and response validation in the FastAPI application. 
These models ensure that incoming requests and outgoing responses adhere to the expected structure 
and data types.

Models:
- AIRequest: Represents the structure of a request sent to the AI endpoint.
- AIResponse: Represents the structure of a response returned by the AI endpoint.
"""

from typing import Optional
from pydantic import BaseModel

class AIRequest(BaseModel):
    """
    Represents the structure of a request sent to the AI endpoint.

    Fields:
    - question (str): The question to be processed by the AI model.
    - model (Optional[str]): The AI model to use (e.g., "openai", "gemini", "custom"). 
      If not provided, the default model will be used.
    """
    question: str
    model: Optional[str] = None

class AIResponse(BaseModel):
    """
    Represents the structure of a response returned by the AI endpoint.

    Fields:
    - answer (str): The answer generated by the AI model in response to the question.
    """
    answer: str
